name: Bug Report
title: "[BUG] "
description: Report a problem you're having
body:
  - type: input
    id: version
    attributes:
      label: Fishstrap Version
      description: "What version of Fishstrap are you using?"
      placeholder: "v2.8.1.3"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What problem did you encounter?
      description: Provide a comprehensive description of the problem you're facing. Don't forget to attach any additional resources you may have, such as log files and screenshots.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Bloxstrap Log
      description: If you're getting a Fishstrap Exception error, upload your log file here. Otherwise, just leave it empty.
      value: "N/A"
      render: text
